# Generated by Django 3.2.18 on 2023-03-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='chat_friend',
            field=models.ManyToManyField(blank=True, null=True, to='users.Profile'),
        ),
    ]
