env:
  - SECRET_KEY=some_secret_key
services:
  web:
    image: python:3.9
    command: python manage.py migrate && python manage.py runworker && daphne core.asgi:application --port $PORT --bind 0.0.0.0 -v2
    env:
      DJANGO_SETTINGS_MODULE: 'core.settings'
      REDIS_URL: 'redis://default:IBVhmzoCOZVoDLaOSul9@containers-us-west-92.railway.app:5903'
      SECRET_KEY: ${{SECRET_KEY}}
    ports:
      - ${{PORT}}:8000
    dependencies:
      - redis
      - postgresql