# Generated by Django 3.2.18 on 2023-03-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0004_auto_20230319_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Image Name', max_length=10000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/chatImages')),
            ],
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, related_name='Images', to='chatApp.ChatImage'),
        ),
    ]
